name: Deploy to vps

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]          # if you ever tag releases
  workflow_dispatch:   # optional: manual trigger

env:
  REGISTRY: ghcr.io
  APP_DIR: /opt/employee-training-plan-app
  VPS_HOST: 57.128.201.144         
  VPS_USER: debian                   
  TAG: ${{ github.ref_name }}        # e.g., v1.2.3

permissions:
  contents: read
  packages: write

jobs:

  deploy:
    name: Deploy to VPS (compose up -d, no .env changes)
    runs-on: ubuntu-latest
    needs: publish

    env:



    steps:
    - uses: actions/checkout@v4
    - name: Copy files via SSH
      uses: appleboy/scp-action@v1
      with:
        host: 57.128.201.144
        username: debian
        key: ${{ secrets.DEPLOY_KEY_VPS }}
        port: 22
        source: "docker-compose.yml"
        target: "docker-compose.yml"

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 57.128.201.144
        username: debian
        key: ${{ secrets.DEPLOY_KEY_VPS }}
        port: 22
        script: |
          cd ${APP_DIR}

          # Login to GHCR if pulling private images
          printf "%s" "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin

          # IMPORTANT: Export TAG only for this command; shell var overrides .env
          TAG="'${TAG}'" docker compose pull
          TAG="'${TAG}'" docker compose up -d --remove-orphans

          docker image prune -f