name: Deploy to vps

on:
  push:
    branches:
      - github-action
  workflow_dispatch:   # optional: manual trigger

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy to VPS (compose up -d, no .env changes)
    runs-on: ubuntu-latest

    env:
      VPS_HOST: 57.128.201.144         
      VPS_USER: debian                   
      APP_DIR: /opt/employee-training-plan-app            # where compose & .env live on the VPS
      TAG: ${{ github.ref_name }}        # e.g., v1.2.3

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 57.128.201.144
        username: debian
        key: ${{ secrets.DEPLOY_KEY_VPS }}
        port: 22
        script: |
          ls -l